name: gh-pages
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install -U \
            furo \
            myst-parser \
            nbsphinx \
            sphinx \
            sphinx-autobuild \
            sphinx-autoapi \
            sphinx-copybutton \
            sphinx_design \
            sphinxcontrib-youtube \
            sphinx-rtd-theme

      - name: Make the Sphinx docs
        run: |
          make -C docs clean
          make -C docs html
          touch ./docs/build/html/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
